### PR TITLE
fix: check length only on unwrapped data

### LINKED ISSUE #316: Cannot read property length of undefined
I am sorry, that might not be a bug, but i am stucked :( Was trying to google or find more info on that problem for 2 days.
I have an http get method in my project that returns an array of objects like this:
````
[ 
    {title: "Title1", id: 5, city: "City1"},
    {title: "Title2", id: 3, city: "City2"},
...
]
myStream$ = this.http.get('/api/getData')
````

http is a casual Angular Http Service that returns an observable.

I tried using pipe that slightly modifies that data and then use that Observable$ with ngu-carousel this way:
````
<div class="component__slider">
   <ngu-carousel
       #myCarousel
       [inputs]="carouselConfig"
       [dataSource]="myStream$ | async"
   >
````

I even simplified it, and tried using only http.get call to supply data to carousel. In either way i get "cannot read length of undefined". Why so? 

My other ngu-carousels in project use Store select observables and work great with async syntax as dataSource, even if i delay data loading from Store(to make it undefined for some seconds). Still, it's ok, ngu-carousel waits till data is emitted and then display slides, but it won't work that way with http.get method

### PR DESCRIPTION
**Pull request by arturovt**
Closes #316

### CODE REVIEW

File: libs/ngu/carousel/src/lib/ngu-carousel/ngu-carousel.component.ts [hunk 1]
```diff
@@ -81,16 +88,26 @@ export class NguCarousel<T>
...
+  set dataSource(data: NguCarouselDataSource) {
     if (data) {
       this._switchDataSource(data);
     }
   }
-  private _dataSource: any;
+  private _dataSource: NguCarouselDataSource = null;
+
+  /**
+   * `_dataSource` allows multiple values to be set considering nullable and
```
Comment (santoshyadavdev) [inline libs/ngu/carousel/src/lib/ngu-carousel/ngu-carousel.component.ts:103]: thank you for explanation

**Review by santoshyadavdev — APPROVED** [review]
